### ISSUE TITLE
Fails to open due to x11 issue.

### ISSUE THREAD

**Issue by rowbawts** [flathub/app.xemu.xemu#1]
When I try and run it I get this.

![Screenshot from 2021-10-05 09-20-35](https://user-images.githubusercontent.com/13012832/136031132-ed5ec552-b90e-463c-b1fe-fd171383b8aa.png)

I checked Flatseal to make sure the Flatpak has x11 permissions and it does so I'm not sure why it doesn't work.

![Screenshot from 2021-10-05 09-21-57](https://user-images.githubusercontent.com/13012832/136031297-7458ca26-f5bd-40e5-a33f-cc1e6d73f8e3.png)

**Comment by j8r** [comment]
This repository will go EOL, due to the renaming from Xemu to xemu. Sorry about that, you'll have to create the issue in the new repository.

**Comment by j8r** [comment]
Are you using Wayland?

**Comment by j8r** [comment]
xemu does not support >Wayland, issue fixed by removing `--socket=wayland`

**Comment by Adnapeht** [comment]
> xemu does not support >Wayland, issue fixed by removing `--socket=wayland`

Hey! I know I'm late to the party on this one, but I'm currently trying to get xemu running on my Raspberry Pi 5. I'm a total noob with this stuff, and I'm not sure where to access the file that '--socket=wayland' is in. I was able to find the manifest.json file and change "--socket=x11" to "--socket=wayland" but that hasn't seemed to change anything. In case this info is relevant I installed xemu via flatpak and I'm running bookworm lite rather than the desktop version.
